recipie_box/config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  root "recipes#index"
end

recipie_box/app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

recipie_box/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

recipie_box/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients
  has_many :directions

  accepts_nested_attributes_for :ingredients,
                                reject_if: proc { |attributes| attributes['name'].blank? },
                                allow_destroy: true

  accepts_nested_attributes_for :directions,
                                reject_if: proc { |attributes| attributes['name'].blank? },
                                allow_destroy: true

  validates :title, :description, :image, presence: true
  has_attached_file :image, styles: { :medium => "400x400#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

recipie_box/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

recipie_box/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipe = Recipe.all.order('created_at DESC')
  end

  def show
  end

  def new
    @recipe = Recipe.new
    @recipe.ingredients.new 
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: "Sucessfully created new Recipe"
    else
      render 'new'
    end

  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy],
    directions_attributes: [:id, :step, :_destroy])
  end


end

recipie_box/app/helpers/application_helper.rb
module ApplicationHelper
end

recipie_box/app/helpers/recipes_helper.rb
module RecipesHelper
end

recipie_box/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Damon's Recipe App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true%>
  <%= javascript_include_tag :cocoon %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top topnav">
  <div class="container topnav">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-collapse-1">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand top-nav" href='/'>Home</a>
    </div>
    <!-- Nav links for top and collapse -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "New Recipe", new_recipe_path %></li>
        <li><%= link_to "something else" %><li>
      </ul>
    </div>
  </div>
</div>
<hr>
<%= yield %>

</body>
</html>

recipie_box/app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: { multipart: true } do |f| %>

<div class="panel-body">
    <%= f.input :title, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
    <%= f.input :image, input_html: { class: 'form-control' } %>

		<div class="row">
			<div class="col-md-6">
				<h3>ingredients</h3>
				<div id="ingredients">
						<%= f.simple_fields_for :ingredients do |ingredient| %>
							<%= render 'ingredients_fields', f: ingredient %>
						<% end %>
						<div class="links">
							<%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default btn-add", :partial => 'ingredients_fields'  %>
						</div>
					</div>
			</div>
			<div class="col-md-6"></div>
		</div>


    <%= f.button :submit, class:"btn btn-primary" %>
</div>
<% end %>

recipie_box/app/views/recipes/_ingredients_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: "form-input form-control" } %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>

    </div>
</div>

recipie_box/app/views/recipes/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

recipie_box/app/views/recipes/index.html.erb
<h1>it has begun!</h1>

<% @recipe.each_slice(3) do |recipes| %>
  <div class="row">
  <% recipes.each do |recipe| %>
    <div class="col-md-4">
      <div class="recipe">
        <div class="image-wrapper">
          <a href="recipes/<%= recipe.id %>"><%= image_tag recipe.image(:medium) %></a>
          <h3><%= link_to recipe.title, recipe %></h3>
        </div>
      </div>
    </div>
  <% end %>
  </div>
<% end %>

recipie_box/app/views/recipes/new.html.erb
<h1> new recipe </h1>

<%= render 'form' %>
<br>

<%= link_to 'Back', root_path, class: "btn btn-default" %>

recipie_box/app/views/recipes/show.html.erb
<div class="container">
<%= image_tag @recipe.image(:medium, class: "recipe-image") %>
<h1><%= @recipe.title %></h1>
<h2><%= @recipe.description %></h2>
<h2>Ingredients</h2>
<% @recipe.ingredients.each do |ingredient| %>
<ul>
  <li><%= ingredient.name %></li>
</ul>
<% end %>
</div>
<%= link_to "Back Home", root_path, class: "btn btn-default" %>
<%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
<%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "sure?"}, class: "btn btn-danger" %>